version: '3.8'

services:
  backend:
    build: ./server
    ports:
      - '5000:5000'

  frontend:
    build: ./client
    ports:
      - '3000:3000'  # Map port 3000 of the container to port 3000 on the host
    depends_on:
      - backend